CANDLEPAIR_HARAMI = 1
CANDLEPAIR_FUKUMI = 2
CANDLEPAIR_GAP = 3
CANDLEPAIR_UPDOW = 4
CANDLEPAIR_DOWNDOW = 5

LINEDIST_ABOVE_FAR = -3
LINEDIST_ABOVE_NEAR = -2
LINEDIST_ABOVE_TOUCHED = -1
LINEDIST_CROSSED = 0 
LINEDIST_BELOW_TOUCHED = 1
LINEDIST_BELOW_NEAR = 2
LINEDIST_BELOW_FAR = 3

LINE_TPTREND = 1
LINE_BTTREND = 2
LINE_MAX = 3
LINE_MIN = 4

EVETYPE_TICK = 1
EVETYPE_ORDER = 2
EVETYPE_SIGNAL = 3

CMD_CREATE_MARKET_ORDER = 1
CMD_CREATE_LIMIT_ORDER = 2
CMD_CREATE_STOP_ORDER = 3
CMD_CANCEL = 4
CMD_ISSUE_ERROR = 5

ORDERTYPE_ORDER = 1
ORDERTYPE_TRADE = 2

ESTATUS_NONE = 0
ESTATUS_ORDER_OPENED = 1
ESTATUS_ORDER_CLOSED = 2
ESTATUS_TRADE_OPENED = 3
ESTATUS_TRADE_CLOSED = 4

TRADING_HISTORY_FLUSH_INTERVAL = 60*60 #move history events to db every hours

SIDE_BUY = 1
SIDE_SELL = -1

TICKTYPE_ONLINE = 1
TICKTYPE_OFFLINE = 2

